version: '2.1'
networks: {}
volumes:
  keys: {}
  resin-data: {}
  config: {}
services:
  mesh.controller:
    build:
      context: ./mesh/controller
    privileged: true
    tty: true
    ports:
      - "8080:8080"
      - "2222:22"
    volumes:
      - "keys:/root/.ssh/"
  system.controller:
    build:
      context: ./system/controller
    privileged: true
    depends_on:
      - mesh.controller
    ports:
      - "2223:22"
    volumes:
      - "keys:/root/.ssh/"
      - "config:/usr/src/config/"
