version: '2.1'
networks: {}
volumes:
  resin-data: {}
services:
  meshcontroller:
    build:
      context: ./meshcontroller
    privileged: true
    tty: true
    ports:
      - "8080:8080"
      - "2222:22"
  systemcontroller:
    build:
      context: ./systemcontroller
    privileged: true
    depends_on:
      - meshcontroller
    ports:
      - "2223:22"
